[book]
authors = ["Nic Lin", "Anton Cheng"]
language = "en"
multilingual = false
src = "src"
title = "Force Inclusion Mechanism"

[output.html]
git-repository-url = "https://github.com/rollup-fortress/uncensored-book"
git-repository-icon = "fa-github" 

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
